import type { Metadata } from 'next'
import { Lato, Londrina_Solid } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer/footer'
import { Toaster } from 'sonner'

const lato = Lato({
  variable: '--font-lato',
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
})

const londrina = Londrina_Solid({
  variable: '--font-londrina',
  weight: ['100', '300', '400', '900'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'CHILL | Movie App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning className={`${lato.variable} ${londrina.variable}`}>
      <body className={`${lato.className} antialiased overflow-x-hidden min-h-screen`}>
        <Navbar />
        <main className='px-5 md:px-20'>{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
